[project]
requires-python = ">=3.10"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
extend-exclude = [
    ".data"
]
extend-include = ["*.ipynb"]
extend-select = ["I"]

# Same as Black.
line-length = 120
indent-width = 4
